version: 2

project_name: wtf_cli

builds:
  - id: wtf_cli_linux
    main: ./cmd/wtf_cli
    binary: wtf_cli
    ldflags:
      - -s -w
      - -X wtf_cli/pkg/version.Version={{.Version}}
      - -X wtf_cli/pkg/version.Commit={{.ShortCommit}}
      - -X wtf_cli/pkg/version.Date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: wtf_cli_linux
    ids:
      - wtf_cli_linux
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE

checksum:
  disable: true
